eav:
    default:
        entity_class: EveryWorkflow\EavBundle\Entity\BaseEntity
        attribute_class: EveryWorkflow\EavBundle\Attribute\BaseAttribute
        attribute_field_mapper_class: EveryWorkflow\EavBundle\Attribute\BaseFieldMapper
        attribute_type: text_attribute
        attribute_field: text_field
    entity_types:
        base_entity: EveryWorkflow\EavBundle\Entity\BaseEntity
    attribute_types:
        text_attribute: EveryWorkflow\EavBundle\Attribute\Type\TextAttribute
        long_text_attribute: EveryWorkflow\EavBundle\Attribute\Type\LongTextAttribute
        select_attribute: EveryWorkflow\EavBundle\Attribute\Type\SelectAttribute
        multi_select_attribute: EveryWorkflow\EavBundle\Attribute\Type\MultiSelectAttribute
        number_attribute: EveryWorkflow\EavBundle\Attribute\Type\NumberAttribute
        currency_attribute: EveryWorkflow\EavBundle\Attribute\Type\CurrencyAttribute
        date_attribute: EveryWorkflow\EavBundle\Attribute\Type\DateAttribute
        date_time_attribute: EveryWorkflow\EavBundle\Attribute\Type\DateTimeAttribute
        boolean_attribute: EveryWorkflow\EavBundle\Attribute\Type\BooleanAttribute
    attribute_forms:
        text_attribute: EveryWorkflow\EavBundle\Form\Attribute\TextAttributeForm
        long_text_attribute: EveryWorkflow\EavBundle\Form\Attribute\LongTextAttributeForm
        select_attribute: EveryWorkflow\EavBundle\Form\Attribute\SelectAttributeForm
        multi_select_attribute: EveryWorkflow\EavBundle\Form\Attribute\MultiSelectAttributeForm
    attribute_type_to_form_field_mapper:
        text_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\TextMapper
        long_text_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\LongTextMapper
        select_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\SelectMapper
        multi_select_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\MultiSelectMapper
        number_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\NumberMapper
        currency_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\CurrencyMapper
        date_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\DateMapper
        date_time_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\DateTimeMapper
        boolean_attribute: EveryWorkflow\EavBundle\Attribute\FieldMapper\BooleanAttribute
